logo: https://www.huzaifaarain.com/wp-content/uploads/2019/05/18581495_1552466228119268_7229590283680579816_n-299x347.jpg
theme: jekyll-theme-minimal
title: Huzaifa Arain
description: Inspired by the legacy of GNU/Linux, Dennis Ritchie, Ken Thompson, Linus Torvalds & Richard Stallman 
plugins:
  - jemoji
